### ISSUE TITLE
'VRCAnimatorSetView' does not exists (After new AV3  update)

### ISSUE THREAD

**Issue by PhaxeNor** [lyuma/Av3Emulator#1]
After the new AV3 update, Set View has been removed and replaced with two new ones.

https://discordapp.com/channels/189511567539306508/730973243904753705/732821042019696661

> - Animator Set View State Behavior has been deprecated and replaced with two other State Behaviors:
>  - Animator Temporary Pose Space should be used for when your avatar swaps to a "sitting mode" or etc-- times where your view shifts due to your pose changing
>  - Animator Remeasure Avatar should be used after you scale your avatar root, to remeasure your avatar's proportions after scaling. This does not scale your viewpoint in real-time-- it

**Comment by lyuma** [comment]
Fixed in v0.4.1
