### ISSUE TITLE
[Suggestion] Add urls in package.json for easier updating

### ISSUE THREAD

**Issue by Aliceto4ki** [lyuma/Av3Emulator#101]
This will allow to properly add it as a community repository in VCC, it will then be easy to see when theres a new version of emulator and update it for all projects with one click
https://vcc.docs.vrchat.com/vpm/packages#vpm-manifest-additions
![image](https://user-images.githubusercontent.com/102074489/232634068-098732ce-3f05-4b62-a5df-bd3e5cc3802b.png)

**Comment by jellejurre** [comment]
Right now we are looking into adding this repository as a curated package. Only if this isn't possible, will we look into making it a community repository. Wouldn't want two versions of the repository floating around.

You can track the progress for this at:
https://github.com/vrchat-community/vpm-listing-curated/pull/5

**Comment by jellejurre** [comment]
Closing this as we are now Curated :D
