### ISSUE TITLE
VRC Viseme state not respected

### ISSUE THREAD

**Issue by SouljaVR** [lyuma/Av3Emulator#109]
Seems if VRC Mouth & Jaw is disabled with tracking control, the viseme slider still controls the viseme blendshapes on the avatar. The intended behaviour should be the Viseme parameter changing values respectively, but the VRC Viseme controller should no longer be active and driving blendshapes on the avatar. All VRC blendshapes should return to 0 while in a disabled state.

**Comment by SouljaVR** [comment]
Ignore the part I said about the Viseme value still changing if mouth & jaw are disabled. VRC functionality actually locks it to 0 if the mouth and jaw are disabled.

**Comment by jellejurre** [comment]
> Ignore the part I said about the Viseme value still changing if mouth & jaw are disabled. VRC functionality actually locks it to 0 if the mouth and jaw are disabled.

I don't think this is quite right, instead it locks it to the current value.

**Comment by SouljaVR** [comment]
Thank you for fixing this Lyuma <3
