### ISSUE TITLE
[Bug] Emulator freezes when there are no active meshes

### ISSUE THREAD

**Issue by kafeijao** [lyuma/Av3Emulator#11]
I have an animation that at one point disables all the meshes. When this happens the emulator becomes unresponsive and doesn't allow me to toggle any parameters anymore. Either using the menu buttons or using the variables at the bottom. Seems all the animator layers pause as well.

An easy way to reproduce is entering play mode with all meshes disabled. Enabling a single mesh manually (while in play mode) makes the emulator work again.

**Comment by lyuma** [comment]
should be fixed in 2.9.0
