### ISSUE TITLE
Adding a builtin parameter to both the expression parameters and a controller blocks this parameter from being changed

### ISSUE THREAD

**Issue by jellejurre** [lyuma/Av3Emulator#121]
Since you shouldnt add builtin parameters to your expression parameters anyways, this isnt too big of an issue, but our behaviour of overwriting values if they change in the animator is kinda weird, since I seem to recall expression parameters not being able to be changed by either OSC or parameter drivers, so our values should be the final value and we should just set the values of the controller to follow them. Will do some more testing on this before implementing.

**Comment by lyuma** [comment]
Just to be clear what we're talking about, are you referring to things like adding a parameter to Expression Parameters named "Viseme" or "GestureLeftWeight"?

if so, what is the expected behavior of this. Do users intentionally do this? Or is it a mistake?

**Comment by jellejurre** [comment]
Yes, exactly. Adding "Viseme" to the expression parameter list and the controller freezes the value in the inspector

There is no reason to do this, as they are synced already, but it's still not great to freeze it. I will do some testing, but I believe those aren't settable with parameter drivers, so we should never set these values anyways, only read from them.

**Comment by jellejurre** [comment]
Fixed on master
