### ISSUE TITLE
VRCExpressionsMenuEditor missing error CS0246

### ISSUE THREAD

**Issue by sriuwu** [lyuma/Av3Emulator#132]
I'm not sure what this means lol 
![image](https://github.com/lyuma/Av3Emulator/assets/127419471/c9bc6546-6cb8-4cda-9668-99be40334df2)

**Comment by lyuma** [comment]
Can you show a picture of your creator companion for your project. And which version of the SDK do you have installed?

**Comment by sriuwu** [comment]
I didn't use VCC. But as for the SDK version, i've been using
2022.10.27.00.35. The only way I got rid of the error was by using an
older version like before. ^^

**Comment by lyuma** [comment]
That SDK is extremely outdated at this point.

I understand many people have been reluctant to change their projects over to VCC. Is there a reason you are still on such an old SDK version?

I will think about how easy it is to add a workaround for 2022 SDK but that will be increasingly untenable over time.

**Comment by sriuwu** [comment]
Yeah I figured it was the issue, the old SDK. So I'm in the process of
migrating right now. Thank you for your responses
