### ISSUE TITLE
Full support for testing non-friend remote player

### ISSUE THREAD

**Issue by anatawa12** [lyuma/Av3Emulator#142]
In #138, `IsOnFriendsList` is implemented as a friend remote players.

we think it's good to add support for non-friend remote clones.

Currently, Av3Emu has ability to create multiple remote clone so I think adding isRemote toggle for each player can be a good option

**Comment by jellejurre** [comment]
This is already done by being able to toggle IsOnFriendList for remote clones I think under Tracking Setup and Other
