### ISSUE TITLE
Null Exception Error

### ISSUE THREAD

**Issue by ven-blackfurr** [lyuma/Av3Emulator#149]
When i go to use the emulator, there are no controls for the base emulator or when paired with gesture manager. I've tried manual installs of both. I've tried by itself. and even with AV3 being the only plugin install. non of the variants work. I got a feeling it's some dum unity setting that is toggled and i can't figure this out.

**Comment by lyuma** [comment]
Thanks for the report! To allow me to fix this, It will be necessary for you to share the exact exception from the console panel.

The best way to do this is if you click on the red error line and copy the entire thing in the bottom half of the console (you see how it shows the full details when you click on an error). But if you can't figure out how to copy the details from the red error, a screenshot may suffice

**Comment by ven-blackfurr** [comment]
I figured it out. VRC Fury. it doesn't play well with AV3

**Comment by jellejurre** [comment]
yeah this is what i was talking about in the group, would be fixed by the latest PR, it's because our emulator reset function isn't working. @lyuma 

@ven-blackfurr to fix it disable "run preprocessor hooks" on the av3 emulator object

**Comment by jellejurre** [comment]
Should be fixed in 3.3.1
