### ISSUE TITLE
InvalidOperationException: Avatar is Null.

### ISSUE THREAD

**Issue by Unitytheproto** [lyuma/Av3Emulator#151]
I tried testing my prefab in unity and it threw thousands of these errors and the emulator didn't function. I'm assuming its because the prefab doesn't have a humanoid rig? older versions of the emulator didn't need this to function though. I hope this can get fixed, thanks!

Full errors below:
ERROR 1:
InvalidOperationException: Avatar is null.
UnityEngine.Animator.GetBoneTransform (UnityEngine.HumanBodyBones humanBoneId) (at <9802f153e66043958995cd88a8668a6e>:0)
Lyuma.Av3Emulator.Runtime.LyumaAv3Runtime.NormalUpdate () (at ./Packages/lyuma.av3emulator/Runtime/Scripts/LyumaAv3Runtime.cs:2042)
Lyuma.Av3Emulator.Runtime.LyumaAv3Runtime.Update () (at ./Packages/lyuma.av3emulator/Runtime/Scripts/LyumaAv3Runtime.cs:1932)

ERROR 2:
InvalidOperationException: Avatar is null.
UnityEngine.Animator.GetBoneTransform (UnityEngine.HumanBodyBones humanBoneId) (at <9802f153e66043958995cd88a8668a6e>:0)
Lyuma.Av3Emulator.Runtime.LyumaAv3Runtime.LateUpdate () (at ./Packages/lyuma.av3emulator/Runtime/Scripts/LyumaAv3Runtime.cs:1808)

**Comment by jellejurre** [comment]
Should be fixed in 3.3.1
