### ISSUE TITLE
Avatar scaling does not scale avatar

### ISSUE THREAD

**Issue by Redageddon** [lyuma/Av3Emulator#164]
Its pinned at 0.79 even if i change Built-in Inputs>Tracking Setup and Other>Avatar Height

**Comment by jellejurre** [comment]
Is avatar scaling enabled?

**Comment by lyuma** [comment]
I might not have tested using the radial menu to affect avatar scale. I would try using the avatar scale slider in the "Lyuma Av3 Runtime" inspector, after making sure avatar scaling is turned on.

**Comment by Redageddon** [comment]
> Is avatar scaling enabled?
yes

> I might not have tested using the radial menu to affect avatar scale. I would try using the avatar scale slider in the "Lyuma Av3 Runtime" inspector, after making sure avatar scaling is turned on.

that is what i did, i don't have the radial menu plugin

**Comment by Redageddon** [comment]
https://github.com/lyuma/Av3Emulator/assets/53098956/8537348a-2b44-4da2-a027-00255f425d09

**Comment by Redageddon** [comment]
The wings move because they are Parent Constrained, but they do not scale either

**Comment by anatawa12** [comment]
I don't know if which is the expected behavior but I found that Avatar Scaling will be applied when I clicked the "Enable Avatar Scaling" button again in my environment.

**Comment by Redageddon** [comment]
Found out what it was, old gogo scaling effect
