### ISSUE TITLE
Animator Auto Live Link is not working in Unity 2019.4.29f1

### ISSUE THREAD

**Issue by OiD-W** [lyuma/Av3Emulator#17]
Hi,

This great piece of software has served excellently.
Unfortunately i seems to have an issue with the Auto Live Link in the Animator not working with Unity version 2019.4.29f1.
Tested with SDK:
VRCSDK3-AVATAR-2021.06.03.14.57_Public
VRCSDK3-AVATAR-2021.08.11.15.16_Public
With an old project from Unity 2018 to 2019, and a new project from Unity 2019.
![image](https://user-images.githubusercontent.com/54041511/132575420-f5830e20-3e7d-433c-9097-0968fdfbc9ea.png)
There is no change in the Animator when running.

I've checked the "NOTE: about viewing animator state from layers other than Base/locomotion:" topic, I am observing the FX under the Base Playable Layer. This was not an issue in 2018.
![image](https://user-images.githubusercontent.com/54041511/132574735-974dd758-e5d1-4a3e-a1fb-f151e818717f.png)

Please let me know if you need more information or I am doing something wrong.

Thanks and regards,

**Comment by lyuma** [comment]
To do this, you should do Tools -> Enable Avatars 3.0 Emulator and then set the "Layer to debug" to FX before entering play mode.

That way, the Animator window will properly link the FX playable.
