### ISSUE TITLE
Unable to upload any Avatar's to VR Chat due to the below errors.

### ISSUE THREAD

**Issue by PaulBoz** [lyuma/Av3Emulator#173]
Recieving the following errors when trying to upload an Avitar:
Packages\lyuma.av3emulator\Runtime\Scripts\LyumaAv3Runtime.cs(1062,16): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
Packages\lyuma.av3emulator\Runtime\Scripts\LyumaAv3Runtime.cs(1183,16): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
Packages\lyuma.av3emulator\Runtime\Scripts\LyumaAv3Runtime.cs(2320,26): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'

**Comment by jellejurre** [comment]
Were working on this one. A reinstall should fix these issues.

**Comment by PaulBoz** [comment]
A reinstall of Jyuma?  I'm a novice, and need some direction on how to reinstall.. and what to reinstall

**Comment by PaulBoz** [comment]
Ok, is there an install package?  I think it came with the model that I downloaded and had issues.

**Comment by jellejurre** [comment]
That's bad

If you don't need the emulator, you can just delete the emulator folder

**Comment by PaulBoz** [comment]
I will have to say for a Novice, I was able to figure it out quickly.  thanks for the help.  You have definitely have been a great help

**Comment by PaulBoz** [comment]
This ticket has been corrected thanks for the help
