### ISSUE TITLE
What is this error and how do i fix?

### ISSUE THREAD

**Issue by LilOozzing** [lyuma/Av3Emulator#182]
Packages\lyuma.av3emulator\Runtime\Scripts\DescriptorCollidersSendersHelper.cs(25,7): error CS0246: The type or namespace name 'VRC' could not be found (are you missing a using directive or an assembly reference?) it gives me this every time i import it in. i kept deleting it and re importing it. and nothing.

**Comment by jellejurre** [comment]
What version of the SDK are you using?

**Comment by LilOozzing** [comment]
im using 2022.3.6f1

**Comment by LilOozzing** [comment]
could it be the modded sdk?

**Comment by jellejurre** [comment]
Yes

We do not support modded sdks, use the latest non-modded sdk for best compatibility

**Comment by LilOozzing** [comment]
alright thanks
