### ISSUE TITLE
Disabling mesh render on animation break the events on emulator

### ISSUE THREAD

**Issue by Malachiel87** [lyuma/Av3Emulator#19]
I noticed when you create a mesh render disabler on menu (for Make the avatar invisible) on emulator after you click the menu toggler the avatar will become invisible fine but if you try to reclick it it will stuck here, instead on vrchat work perfectly fine.
![unknown](https://user-images.githubusercontent.com/3611852/137268178-3e9fee08-c865-44a3-810c-f0211c50947e.png)

**Comment by lyuma** [comment]
Actually to be more accurate, in VRChat it will also break for remote players: your avatar will just disappear permanently.

The emulator is trying to show you what other players will see in this case... though I should change it so the local copy enables "Update when Offscreen" and remote copies disable "Update when Offscreen" to match ingame more accurately.

**Comment by lyuma** [comment]
handling of updateWhenOffscreen was added a long time ago. I'm going to close this issue, since I'm not convinced it is a bug in terms of emulation being different from in-world
