### ISSUE TITLE
can this plugin even render physical movements via vr controller?

### ISSUE THREAD

**Issue by blul1ghtz** [lyuma/Av3Emulator#193]
ok soo this plugin is really hard to use and i just wanna know if its possible to move characters in unity using this with open xr or oculus cus iv been trynna do it fvor the last 20 minutes and i cant get anything going

**Comment by jellejurre** [comment]
I don't think this is possible to emulate vr (either controllers, headset or trackers) movement in the emulator no

**Comment by blul1ghtz** [comment]
oh thats a bummer, thanks for quick answer
