### ISSUE TITLE
nothing works when you click on it!

### ISSUE THREAD

**Issue by IIXDINE** [lyuma/Av3Emulator#196]
https://github.com/user-attachments/assets/ed4f3985-b132-4d39-ae22-efa713bf19b5

please fix the bug or tell me how i can fix it if its on my end!!

**Comment by jellejurre** [comment]
Does it work in the game?

**Comment by IIXDINE** [comment]
I haven’t checked! But it was before the bug came. I can check now!

Reply to this email directly, view it on GitHub
<https://github.com/lyuma/Av3Emulator/issues/196#issuecomment-2510288687>,
or unsubscribe

**Comment by IIXDINE** [comment]
@jellejurre  yes it works in game

**Comment by jellejurre** [comment]
Is there anything in the console

**Comment by IIXDINE** [comment]
@jellejurre  yes but when you click on anything nothing happens

**Comment by jellejurre** [comment]
Any errors in the console

**Comment by IIXDINE** [comment]
@jellejurre  about physbones yes but nothing about the av3 package not working

**Comment by IIXDINE** [comment]
@kakuchrome youre right!

**Comment by HatsuneSora** [comment]
Yes, the version AV3 Emulator 3.4.6 works itself with no problems, WITHOUT the Gesture Manager. And the Gesture Manager 3.9.3 works fine without Av3 Emulator. But if you Play Av3 Emulator 3.4.6 with Gesture Manager 3.9.3, The gesture manager menu with Av3 Emulator didnt works. But it works fine if you install AV3 Emulator 3.4.6 with Gesture Manager 3.9.2. I dont know if its problem of Av3 Emulator or the Gesture Manager, But there is an incompatibility problem between these two versions.

**Comment by jellejurre** [comment]
will be fixed once https://github.com/lyuma/Av3Emulator/pull/198 gets released

**Comment by IIXDINE** [comment]
@jellejurre alright take your time dont rush yourself!!!

**Comment by lyuma** [comment]
We have released version 3.4.7 with that fix - it can be downloaded from the Releases page until VCC is updated.
