### ISSUE TITLE
[Bug] Animation-based LipSync is not work in 3.4.7

### ISSUE THREAD

**Issue by c-colloid** [lyuma/Av3Emulator#199]
The update 
> Attempt to override viseme blend shapes in LateUpdate so they override animation.

in 3.7.4 kill the Animation-based LipSync emulation when the property of AvatarDescriptor is set to `Viseme Blend Shape`.
However, this is not correct behavior, because the animation can override the AvatarDescriptor's LipSync system in VRC.

**Comment by c-colloid** [comment]
I am aware of a bug that when a BlendShape that is set to LipSync in AvatarDescriptor is registered to an animation, the LipSync of AvatarDescriptor stops, but I am not aware of the behavior of overwriting the animation.
I don't know why he made that conclusion either.

I am creating an extension that will install Animation-based LipSync and an extension that will install Animation-based blink.
These have been confirmed to work on my side by overriding the AvatarDescriptor settings, and I have applied them to other people's avatars for sale without any problems.

Reference materia:
LipSyncSetter
https://store.vket.com/ja/items/6904
EyeJigglingGenerator
[EyeJigglingGenerator v0.2.7.zip](https://github.com/user-attachments/files/18192430/EyeJigglingGenerator.v0.2.7.zip)

**Comment by lyuma** [comment]
Yeah so the problem was that the "animator tracking control" was being ignored when set to animation. This bug should be fixed in 3.4.8 - it can be installed from [the releases page](https://github.com/lyuma/Av3Emulator/releases)

Thanks for reporting and for your patience.
