### ISSUE TITLE
Merging FX layers with Mixed Write defaults is Breaking Facial Expressions

### ISSUE THREAD

**Issue by Faith13vr** [lyuma/Av3Emulator#20]
As Mentioned before in a previous Bug, Facial expressions are breaking when merging FX layers. 

The Merger has 3 options and none work

Mixed write default merge - Breaks
Set write defaults on - Breaks
Set write defaults off - Breaks

Its specifically noticed when the Avatar has a Tongue added for example OniiGirii's Tongue.

**Comment by jellejurre** [comment]
I think this was fixed a while ago but the issue wasn't closed. If this issue still persists, feel free to reopen this or make a new issue.
