### ISSUE TITLE
Eye gaze emulation overrides VRCFT

### ISSUE THREAD

**Issue by MooshPaw** [lyuma/Av3Emulator#203]
I also haven't seen an option to disable the eye gaze based on mouse movement which would be good to have, but yeah

I was no longer able to test VRCFT eye gaze as the mouse movement would override the VRCFT or OSC movements

There is a possibility that I couldn't get the OSC messages to transfer correctly on this version of AV3 as I only got EyesClosedAmount and Eye movement to transfer through OSC, and the avatar parameters didn't load on the VRCFT app, this said, the menu toggles that disable VRChat native eye gaze wouldn't disable the AV3 mouse eye gaze, leading me to believe that if the OSC messages transfered correctly, it would either keep being overwritten or would add both eye rotations

**Comment by MooshPaw** [comment]
Ok I managed to get OSC data by sending it through VRChat rather than VRCFT

Can confirm that the OSC data is overwritten by the mouse movement and the default VRChat eye gaze takes priority instead

**Comment by lyuma** [comment]
Should be fixed in 3.4.8 - it can be installed from [the releases page](https://github.com/lyuma/Av3Emulator/releases)

**Comment by MooshPaw** [comment]
Thank you, i did some testing and it seems that having the eyes set to "animation" defaults to having the eyes closed
I can confirm this is due to wrong emulation on Av3 as disabling the eyelids on the avatar descriptor fixes the issue
![imagen](https://github.com/user-attachments/assets/0c6c5f54-5321-4592-a00d-c33ac3b901bb)

**Comment by MooshPaw** [comment]
Ok nevermind, the issue fixed itself, don't know what it was, thanks for the fix!
