### ISSUE TITLE
When both GestureManager's Latest & This' GM Ver Are Installed, It Breaks.

### ISSUE THREAD

**Issue by MistressPlague** [lyuma/Av3Emulator#23]
Not much else to say really; 
![image](https://user-images.githubusercontent.com/36628963/145716728-ae51f6c9-f7f6-49b0-a37c-af235ea67605.png)
![image](https://user-images.githubusercontent.com/36628963/145716741-777dc842-0b26-4d09-af43-7aba73555861.png)
![image](https://user-images.githubusercontent.com/36628963/145716746-edccbf36-b28d-4128-bc5f-24a6651e0ecc.png)

**Comment by lyuma** [comment]
Thanks for the report. I didn't notice GM 3.3 was released. I would stick with 3.2 for now until this issue is resolved, or use the non-GM version of avatar 3 emulator. Sorry about that!

**Comment by lyuma** [comment]
I was using that return value for the wrong thing. It should be fixed now,

In the future, if I hit more issues integrating with GM that I might essentially need to embed a fork of GestureManager just for rendering the radial menu.
