### ISSUE TITLE
Allow disabling mirror clone; make it not show up during upload

### ISSUE THREAD

**Issue by lyuma** [lyuma/Av3Emulator#25]
Mirror clone currently causes two VRCCam's to be created during upload which is silly

**Comment by absolutory** [comment]
This is still happening - happens for my every upload.

**Comment by c-colloid** [comment]
I'm in the same situation. look at the attached image. when I want to overwrite an avatar I've already uploaded, the "NewAvatarCreation" screen comes to the front and the "UpdateAvatar" screen is hidden. When I want to overwrite an avatar I've already uploaded, the "NewAvatarCreation" screen comes to the front and the "UpdateAvatar" screen is hidden. 
! [Screenshot 1](https://user-images.githubusercontent.com/28706700/155265057-bf6c1c30-6fa1-48fe-b547-7695c2aadebf.png) ! [Screenshot 2](https://user-images.githubusercontent.com/28706700/155265067-13b09e91-73e3-4dd9-af6d-9c7c060a9c52.png) 
This has increased. You can turn it off by hiding the "VRCSDK" but it's very distracting so please make an option to not show "MirrorReflectionClone". 
! [Screenshot 3](https://user-images.githubusercontent.com/28706700/155265147-1822f7d9-f639-4473-b7d6-682d0da5fc41.png) ! [Screenshot 4](https://user-images.githubusercontent.com/28706700/155265454-3fbfa171-bc21-485f-96ae-ddcede12a6d4.png)

**Comment by lyuma** [comment]
You can disable mirror clone by changing settings on Emulator Control before going to play mode.

In addition, I fixed the errors which happen during upload, even if you leave them on.
