### ISSUE TITLE
Console spamming NullReferenceException

### ISSUE THREAD

**Issue by FireWolf-kPanel** [lyuma/Av3Emulator#28]
Upon using the Kita'vali package with Av3 I got this message spamming the console

`NullReferenceException: Object reference not set to an instance of an object
LyumaAv3Runtime.Update () (at Assets/Lyuma/Av3Emulator/Scripts/LyumaAv3Runtime.cs:1695)`

**Comment by lyuma** [comment]
This used to happen when VRCSDK Examples was not installed at the right location, or one of your playable layers was set to null. Should be fixed now in 2.9.6
