### ISSUE TITLE
Gesture menu compact options disables itself when toggling radial menu on and off

### ISSUE THREAD

**Issue by synergiance** [lyuma/Av3Emulator#30]
When toggling the radial menu visualization, the compact options state is not preserved at runtime.

How to reproduce:
1 - Set up emulator and avatar (if you haven't already)
2 - Enter play mode and select avatar in hierarchy
3 - Ensure radial menu is toggled off
4 - Check Compact Options in the Gesture Manager component (if unchecked)
5 - Click "GestureManager Radial Menu" button
6 - Click button again to turn it off
7 - Note how Compact Options toggle is now unchecked

**Comment by lyuma** [comment]
My attempt to fix icons ended up breaking non-compat menu :-p So I guess it's not currently a bug since it is always Compat Menu now. Sorry
