### ISSUE TITLE
error CS0234

### ISSUE THREAD

**Issue by ChinatsuHS** [lyuma/Av3Emulator#31]
On the latest SDK with the latest lyumaAV3Emumator this error appears when building & uploading: Assets\Lyuma\Av3Emulator\Scripts\A3EOSCConfiguration.cs(142,60): error CS0234: The type or namespace name 'VRC_SdkBuilder' does not exist in the namespace 'VRC.SDKBase.Editor' (are you missing an assembly reference?)

it prevents the process from continuing even with the tool disabled.

Greetings MDnight

**Comment by lyuma** [comment]
Fixed in 2.9.5
