### ISSUE TITLE
Expression Menu HTML Formatting

### ISSUE THREAD

**Issue by NotAKidOnSteam** [lyuma/Av3Emulator#33]
You can format the VRChat expression menu & expression wing text with HTML codes. While it is probably unintentional, it is useful.

The Av3Emulator does not display the formatting of the menu text, so it displays as raw HTML.

It would be nice if the emulator properly displayed HTML formatting for both visual clutter and testing purposes.

**Comment by lyuma** [comment]
Sorry, I forgot to add this to the legacy menu in the latest update.

For now, I'd recommend using the GestureManager integration and enable the GestureManager Radial Menu (button in top right corner). It should show rich text correctly:
![Picture of editing VRCExpressionMenu and GestureManager in two inspectors](https://user-images.githubusercontent.com/39946030/165026115-d0edd626-7b1e-4568-8606-6e2089d169a5.png)

**Comment by jellejurre** [comment]
Added in last release
