### ISSUE TITLE
Only see the tools thing.

### ISSUE THREAD

**Issue by GhostsReturn** [lyuma/Av3Emulator#35]
So, all I see is the tools thing in the top corner, I'm not sure how to fix this, I've even switched projects multiple times.

[ ](url
![5c9db9572cfbcaae09dba22e97edf14f](https://user-images.githubusercontent.com/101891212/159054030-61d523e0-3d58-4eae-94ff-b94186aaa54a.png)
)

**Comment by lyuma** [comment]
Do you see Enable Avatars 3.0 Emulator when you click on Tools?
![Showing Unity Tools menu expanded, with Enable Avatars 3.0 Emulator highlighted](https://user-images.githubusercontent.com/39946030/165025611-687c81bb-c6ad-453f-9945-37c8de5d2d44.png)

**Comment by jellejurre** [comment]
Closing as inactive. Feel free to reopen if you still can't work it out.
