### ISSUE TITLE
OSC Enable dosn't work. 

### ISSUE THREAD

**Issue by marcus-universe** [lyuma/Av3Emulator#37]
Hi, I discovered an issue with the newest version von Av3Emulator v2.9.7. I tested it on my project and on a clean new project with 2 different Avatars on each one. Everything like Gesture Manager and stuff work but if I enable OSC on the Avatar I get this error and no logging of OSC receives. 
![image](https://user-images.githubusercontent.com/26997041/160236893-0818f86b-cad6-42d3-bdcf-4b40b1378203.png)

I use Unity in german so the error says "An existing connection has been closed by the remote host."
I tested older versions till I get to v2.3a1. This version seems to work. 
My Unity Version is 2019.4.31f1

Here the configuration:
![image](https://user-images.githubusercontent.com/26997041/160237410-225f1e33-bdc4-4d71-a5be-21f3e3a79a82.png)
![image](https://user-images.githubusercontent.com/26997041/160237319-d040f38e-81c7-44ce-9af6-c71ee9ac5a4e.png)

OSC Sending I use Touch Designer. I only use it to send Midi Data to OSC over Port 9000. No listening on 9001 or logging on to other software. 

Hope this helps. Ask me if you need more Infos 😊

**Comment by lyuma** [comment]
Have you figured out any solution to this? I noticed some people found that just opening up TouchOSC in the background avoided this problem, but that's a weird workaround.

**Comment by marcus-universe** [comment]
> Have you figured out any solution to this? I noticed some people found that just opening up TouchOSC in the background avoided this problem, but that's a weird workaround.

With the new update, it works fine. Just install the [v2.9.8 of Av3Emulator](https://github.com/lyuma/Av3Emulator/releases/tag/v2.9.8) in your project ;)
