### ISSUE TITLE
Incompatible with VRLabs Ragdoll system | (Maybe VRLabs in General)

### ISSUE THREAD

**Issue by Miniko39** [lyuma/Av3Emulator#38]
In the 2 pictures below, is proof of the Lyuma script while in Unity's play mode. The script itself still functions, but the radial/lite menu no longer pops up while in play mode. This happened after I applied a Ragdoll System to the avatar the lyuma script affects.

![Lyuma Bug pic 21](https://user-images.githubusercontent.com/102616437/160669767-29710c4f-5098-4cd7-8d67-2114d3c778da.PNG)
![Lyuma Bug 1](https://user-images.githubusercontent.com/102616437/160669770-a440e3ba-d3cc-4c66-9dd0-1d9dc71505c2.PNG)

**Comment by lyuma** [comment]
Would it be possible to reproduce this on the latest version (VCC?) include output from the console.

**Comment by jellejurre** [comment]
Closed due to no response and inability to recreate. If this issue persists, feel free to reopen this issue or create a new one.
