### ISSUE TITLE
As soon as LyuamaA3Emulator is imported, avatar cant be uploaded.

### ISSUE THREAD

**Issue by oragres** [lyuma/Av3Emulator#42]
As soon as LyuamaA3Emulator is imported, avatar cant be uploaded.

New Avatar Creation screen is not popping up and when i go to the "Game" Tab i cant click anywhere.

![image](https://user-images.githubusercontent.com/95907232/162616576-dcfd3c87-e0ec-428d-a243-9d98a8ccc520.png)

Only solution is to delete LyumaAv3Emulator_v2.9.7 package but i need it for the VRLabs Ragdoll system...

What can i do?

**Comment by lyuma** [comment]
I don't think the error stopping upload is on the screen.

I see an error from Pumkin's on the log. Old versions of PumkinsAvatarTools are incompatible with the latest VRCSDK - I would suggest updating that and see if it solves things. If not, try clearing the console and look for any errors that won't clear.

**Comment by jellejurre** [comment]
Closed as I'm assuming it's not an emulator issue. If it is, feel free to reopen with more information if you think it is.
