### ISSUE TITLE
Console error spam

### ISSUE THREAD

**Issue by Mangos02** [lyuma/Av3Emulator#46]
when in play mode ever since the sdk update im getting all these errors and a lot of things arent working properly
![Unity_D2Em6SVbeZ](https://user-images.githubusercontent.com/12200023/164994274-5bb39c22-5b7f-4e4c-9ba8-ad789f21c5ea.png)
)

**Comment by lyuma** [comment]
This can happen if you have the same parameter on two different playable controllers with a different type (Int / Float / Bool)

I don't currently have a fix for this, but it would be good to make your animators consistent with each other if you can.

if this isn't the issue, could you explain more of your setup? does it happen if you remove Playable controllers other than FX?

**Comment by Mangos02** [comment]
my problem was with an older version of Dervali Laying / Sitting Animation Prefab causing all the errors
