### ISSUE TITLE
Failed to resolve animator controller

### ISSUE THREAD

**Issue by Kieaer** [lyuma/Av3Emulator#52]
![image](https://user-images.githubusercontent.com/44261958/169292914-1eb4a31b-0856-40c7-bda9-945f193f6c76.png)
This error occurs when the VRC SDK now uses the package manager.

**Comment by NotAKidOnSteam** [comment]
The default animators are now at a different path which I assume changes with each SDK update. 
> Assets/Samples/VRChat SDK - Avatars/3.0.4/AV3 Demo Assets/Animation/Controllers

Av3Emulator would need to account for version differences and those who delete the Samples folder.
https://github.com/lyuma/Av3Emulator/blob/6142d8b5a3bfed41a35c874824c54e3f92664bf3/Editor/LyumaAv3EditorSupport.cs#L62-L74

A canny should be made requesting the SDK examples be their own package or included with the VRChat SDK - Avatars package to simplify things.
