### ISSUE TITLE
(v2.9.9) Floats can not be driven via puppets in built-in gesture manager

### ISSUE THREAD

**Issue by Asovrix** [lyuma/Av3Emulator#53]
Radial or TwoAxis (haven't tested FourAxis) puppets appear to be not able to drive float parameters assigned to them in menus.
Videos describing the issue:

https://user-images.githubusercontent.com/44006686/172069350-94d56b49-078a-4806-a61f-314bab6aa994.mp4

https://user-images.githubusercontent.com/44006686/172069356-e483c837-dce4-4cd0-8488-f705eb8ae3cf.mp4

This is happening on a version without BlackStartx's Gesture Manager (distributed as zip archive from Releases).
Other people who use that script report that it doesn't happen if you use above mentioned script.

Issue wasn't happening on version 2.9.8 with the exact same avatar.

**Comment by lyuma** [comment]
Fixed in 2.9.10. I hadn't tested the legacy menu after fixing the animated animator parameter issue.

Thanks for the report.
