### ISSUE TITLE
'VRCAvatarParameterDriver' does not contain a definition for 'OnApplySettings'

### ISSUE THREAD

**Issue by RyanDavanzo** [lyuma/Av3Emulator#55]
Full error here:

Assets\Lyuma\Av3Emulator\Scripts\LyumaAv3Runtime.cs(500,34): error CS0117: 'VRCAvatarParameterDriver' does not contain a definition for 'OnApplySettings'

I can't enter play mode while this error is here ;w;

**Comment by lyuma** [comment]
Please download the latest build from https://github.com/lyuma/Av3Emulator/releases

also, make sure you have updated your VRCSDK to the latest version.
If you are still having trouble with this or other scripts in the project, look over the VRC release notes for the most recent update for some instructions on how to address these error.

**Comment by RyanDavanzo** [comment]
I did. Everything is updated.

**Comment by lyuma** [comment]
This error means that the SDK is out of date or not properly installed. Please download the latest. If using creator companion, it might have bugs preventing update.

If you are unable to upgrade VRCSDK to 2022.06.03 or newer, the only other option is to revert Av3Emulator to 2.9.8 here: https://github.com/lyuma/Av3Emulator/releases/tag/v2.9.8

**Comment by RyanDavanzo** [comment]
Alrighty, reverting to 2.9.8 worked. Thanks :3
