### ISSUE TITLE
Disable Shadow and Mirror clone by default

### ISSUE THREAD

**Issue by NotAKidOnSteam** [lyuma/Av3Emulator#57]
They should be disabled by default due to their more advanced nature. I find myself disabling them constantly as I don't keep the Avatars 3.0 Emulator Control prefab in my scene once done with debugging.

**Comment by lyuma** [comment]
I think I need a settings window so you can configure project-wide defaults and I'm less dependent on keeping it in the scene -- and then it wouldn't be necessary to add that control thing to the scene every time you hit play.

Thanks for the feedback.

**Comment by lyuma** [comment]
We added a settings window. I also made them greyed out and improved some of the visibility settings so they shouldn't be in the way as much. I think it's important to be able to replicate how avatars really work, so I want them on by default.

But now it is possible to turn them off project-wide in the new settings window, so I think that's sufficient to close this issue.
