### ISSUE TITLE
SDK Compatibility Issue?

### ISSUE THREAD

**Issue by Shadow-Wolfe** [lyuma/Av3Emulator#58]
So I recently went to update my avatar's version and avatar SDK, but a while after, VRC's SDK just suddenly went into "Reload SDK" mode and wouldn't reload. Many attempts (and hours) later, I just figured out that the emulator might be a possible cause? In a completely fresh project, I first installed the VRC Avatar SDK right from VRC's site, "VRCSDK3-AVATAR-2022.06.03.00.04_Public" and the latest download of the avatar emulator, dated June 5th (v2.9.10). Upon closing and reopening that fresh project, VRC's SDK went right into that softlock state of "Reload SDK." Attached is a screenshot of the errors I encountered upon loading.

It wouldn't surprise me if the actual SDK was just being a massive pain for some reason - I'm late to Physbones but I want them, dang it - but I figured I'd mention it here since this is what I've come across, especially in a fresh project.
![image](https://user-images.githubusercontent.com/76074119/180630743-38a12aa7-c83a-40fc-97ca-89ff8956a8af.png)

**Comment by lyuma** [comment]
Hi @Shadow-Wolfe, it seems you somehow have an old version of the Av3Emulator, but you're getting an error on line 293 that simply no longer exists: "Initialize" was replaced with "OnApplySettings".

So I'd encourage you to try again to install the latest emulator. maybe start by removing the old one and make sure your project is healthy, and then try installing 2.9.10 again.

Thanks!

**Comment by Shadow-Wolfe** [comment]
Yeahhh, somehow I managed to download 2.2.2 - gotta love it when my browser history defaults to the link instead of the page. Luckily nothing went wrong this time, thanks!
