### ISSUE TITLE
Incorrect handling of local parameter drivers with mirror clones

### ISSUE THREAD

**Issue by bdunderscore** [lyuma/Av3Emulator#60]
When a parameter driver is used to drive an unsynced FX layer parameter in VRChat, the parameter is also written to the FX layer animator on the mirror clone. However, in av3emu, the parameter is not written to the mirror clone.

Here is a complete test avatar demonstrating this issue. It contains a cube which is initialized to have a random hue. In client, both first-person and mirror clone avatars have the same hue, while in av3emu the mirror clone has a black cube, indicating that the parameter drivers were not applied to the mirror clone at all.

[test_local_param_drivers.zip](https://github.com/lyuma/Av3Emulator/files/9229877/test_local_param_drivers.zip)

**Comment by jellejurre** [comment]
Managed to reproduce. This only happens when the driven parameter isn't a synced parameter.

**Comment by jellejurre** [comment]
This was fixed by #97
