### ISSUE TITLE
[Bug] Internal gesture manager broken by latest SDK

### ISSUE THREAD

**Issue by Myrkie** [lyuma/Av3Emulator#65]
the internal gesture manager is broken by latest vrcsdk update, 3.6 will cause compiler issues for lyuma 2.9.10 you will have to manually update the included gesture manager version to V3.7 to not have any compiler errors, [GestureManager-3.7](https://github.com/BlackStartx/VRC-Gesture-Manager/releases/tag/v3.7)

**Comment by lyuma** [comment]
Aha, that explains some of the recent reports. I will try and get to that some time today

**Comment by Myrkie** [comment]
thanks, its just a simply fixed by updating the internal GestureManager as BlackStartx has already fixed it on their end, issue was only caused by GestureManager not by lyuma. ill keep this issue open until the next release is out

**Comment by lyuma** [comment]
Thanks for reporting this and alerting me to the newly-released GestureManager 3.7. I have bundled it in the latest update! Let me know if there are still issues.
