### ISSUE TITLE
The Animator Controller (EmptyController) you have used is not valid. Animations will not play

### ISSUE THREAD

**Issue by gjc1017** [lyuma/Av3Emulator#78]
The Animator Controller (EmptyController) you have used is not valid. Animations will not play
UnityEngine.StackTraceUtility:ExtractStackTrace ()
LyumaAv3Emulator:Awake () (at Assets/Lyuma/Av3Emulator/Scripts/LyumaAv3Emulator.cs:65)

**Comment by jellejurre** [comment]
Fixed by last release
