### ISSUE TITLE
VRC Avatar Parameter driver does not copy integers correctly

### ISSUE THREAD

**Issue by Happyrobot33** [lyuma/Av3Emulator#79]
Currently, if you have a large integer like 22121111, and use a parameter driver to copy it to another parameter, it will instead become 22121112
![OMG WHY](https://user-images.githubusercontent.com/32679887/208727226-ea10eaa3-ead3-4030-b39f-7fcfb8f0f937.PNG)
My guess why this is happening is that there is a float conversion going on that shouldnt be, as both the source and destination here are integers, so it should be direct

I understand this is not in the 0-255 range that can be used to sync parameters, but having large numbers like this is useful for calculations, and this behaviour makes no sense

Cross post on vrchats canny as I am not 100% sure if this is a VRC bug or a lyuma bug https://feedback.vrchat.com/bug-reports/p/vrc-avatar-parameter-driver-does-not-copy-integers-correctly

**Comment by Happyrobot33** [comment]
if I am understanding the code correctly, it appears to be related to [this line](https://github.com/lyuma/Av3Emulator/blob/master/Scripts/LyumaAv3Runtime.cs#L573) where it does a unnecesary float to int conversion. However I dont know if this is how VRCs implementation works or not

**Comment by jellejurre** [comment]
Since this is a tracked bug, I'm assumign this is on the vrchat side, if not, feel free to reopen
