### ISSUE TITLE
VRC CreatorCompanion SDK Issue

### ISSUE THREAD

**Issue by Waterspark63** [lyuma/Av3Emulator#80]
It seems like the default guid for the action layer when you use the VRC-CC client is different, as when I went into play mode with the Av3Em, it kept saying that the action layer was unable to be resolved, and the guid was different for the action layer when I looked at the meta file, and the default guid stored in the LyumaAv3EditorSupport.cs
(Also, I ended up changing the "Assets/VRC/..." paths to "Packages/com.vrchat.avatars/..", not entirely sure if the old path is broken or not, but the VRC SDK isn't in Assets anymore, at least when you use the CC.)

**Comment by anatawa12** [comment]
Fixed in #68. Thank you for reporting.
