### ISSUE TITLE
 Av3Emulator breaks any of my projects

### ISSUE THREAD

**Issue by blackorbit1** [lyuma/Av3Emulator#83]
Hey there 👋 I wanted to thank you for developing your tool, although unfortunately I haven't been able to use it successfully yet. Every time I try to import it into one of my projects, it ends up breaking it and I can't even enter play mode anymore.
It seems that the tool installation is failing because I can't find any button to access it either.

![image](https://user-images.githubusercontent.com/38140797/221924610-c225b32e-83b8-4dd3-b6b7-3292cf13e634.png)

# Steps to reproduce

1. Create an empty avatar project with the creator companion (everything up to date)
2. import the latest version of Av3Emulator

**Comment by anatawa12** [comment]
It looks you're using VPM version of GestureManager and current released versions of Av3Emulator doesn't support that yet. 

VPM version of GestureManager support is added in #81. 

Thank you for reporting.
