### ISSUE TITLE
Regenerating GUIDs will break existing project with Av3Emulator

### ISSUE THREAD

**Issue by anatawa12** [lyuma/Av3Emulator#87]
Relates f369f7159885421be924b9fb080db303399a8a11

<img width="329" alt="image" src="https://user-images.githubusercontent.com/22656849/222956756-7f8d4a8a-87b6-4b79-b42c-4c4c4703f07e.png">

In most tools migrates to VPM, regenrating GUID is not performed. in my opinion, It's better to make warning on importing av3emulator unitypackage instead of regenerating GUIDs.

**Comment by anatawa12** [comment]
Another fix is in #90

**Comment by jellejurre** [comment]
Fixed
