### ISSUE TITLE
[Bug?] When Facial Expression in the FX layer Write Defaults are on, AV3Emulator treats them as if they are off.

### ISSUE THREAD

**Issue by Provini** [lyuma/Av3Emulator#9]
This causes facial expressions to mess up when messing with them in the emulator if they aren't set up with write defaults off in mind. Facial Expressions look fine in-game or just testing it with the FX layer alone in unity without the emulator.

I do know it's highly recommended to do Write Defaults off on everything, but it was worth reporting anyways. ^^

**Comment by jellejurre** [comment]
I think this was fixed a while ago but the issue wasn't closed. If this issue still persists, feel free to reopen this or make a new issue.
